texts = {
  { l = "en-US", t = "a simple test" },
  { l = "fr", t = "je veux manger de fromage" },
  { l = "fr", t = "Run of site" },
  { l = "fr", t = "Run of site" },
  { l = "en-US", t = "B.U.D.S." },
  { l = "en-US", t = "License Renew" },
  { l = "en-GB", t = "[Please note that |However,] the weather [is good|is still favorable|is still good] [in {city}|in the city of {city}]." },
  { l = "en-GB", t = "[In this city|In that city|Here|There], the temperatures [are|are still] [pleasing|attractive|pleasing|suitable] and allow you [to visit and enjoy the sun.|to visit - and why not do a bit of sunbathing in the sun!|enjoy the sun and sightseeing in good conditions.]" },
  { l = "en-GB", t = "[Please note that|However,|Apart from of <t0>{cities}<t1>,] the weather [is good|is still favorable|is still good] [in {cities}|in the cities of {cities}]." },
  { l = "en-GB", t = "[In these cities|Around here|In these areas], temperatures [are|are still] [pleasing|attractive|pleasing|suitable] and allow you [to visit and enjoy the sun.|to visit - and why not do a bit of sunbathing in the sun!|enjoy the sun and sightseeing in good conditions.]" },
  { l = "en-GB", t = "If you do not go [for the sun or the beach|lazing in the sun|to spend your time in a lounger by the pool|for the sun and blue sky], but, for example [for cultural tours or hiking|to discover the heritage|to go sightseeing|for hiking|to go sightseeing around], the city <t0>{city}<t1> have a [quite correct|just ok|ok but correct|OK but just acceptable|decent enough] weather for [it|that|this kind of activity] in <t2>{month}<t3>." },
  { l = "en-GB", t = "If you do not go [for the sun or the beach|lazing in the sun|to spend your time in a lounger by the pool|the sun and blue sky], but, for example [for cultural tours or hiking|to discover the heritage|to go sightseeing|for hiking|to go sightseeing around], the cities of <t0>{cities}<t1> have a [quite correct|just ok|ok but correct|OK but just acceptable|decent enough] weather for [it|that|this kind of activity] in <t2>{month}<t3>." },
  { l = "en-GB", t = "[Finally|Eventually], [avoid going|we advise you to avoid you get|it is not advisable to travel] in <t0>{city}<t1> [that month|in {month}] because the climate is [rather|frankly|pretty|] [unfavorable|bad]." },
  { l = "en-GB", t = "[Finally|Eventually], [avoid going|we advise you to avoid you get|it is not advisable to travel] [in <t0>{cities}<t1>|in the cities of {cities}] [that month|in {month}] because the climate is [rather|frankly|pretty|] [unfavorable|bad]." },
  { l = "en-GB", t = "[On the month of {month}|In {month}] the <t0>weather in {country}<t1> is [perfect|just perfect] everywhere." },
  { l = "en-GB", t = "Thus, in {city} [all the conditions are right for you to|the conditions are met so that you can|these ideal weather conditions will allow you to|these ideal weather conditions will allow you to] [enjoy a maximum|enjoy 100%|live fully|savor fully] [your trip|your travel|your vacations|your holidays]: the sun is [here|guaranteed], [it rains very little|rainfall is scarce|precipitations are scarce] and the humidity [is not too high|is bearable|is endurable]." },
  { l = "en-GB", t = "It is therefore the ideal month to [visit|travel to|go to] this city!" },
  { l = "es", t = "Un breve sondeo en la redacción y el resultado es claro: los británicos nos encantan." },
  { l = "es", t = "Las hay que se vuelven locas con Benedict Cumberbatch, que sueñan cada noche con Theo James o que adoran a Robert Pattinson por encima de todas las cosas." },
  { l = "es", t = "Pero, sea cual sea nuestro favorito, no podemos negar que los chicos del Reino Unido tienen algo que no tienen un francés, un italiano o un alemán, y no es un chiste." },
  { l = "es", t = "¿Será el acento?" },
  { l = "es", t = "¿Será el estilo?" },
  { l = "es", t = "Todo cuenta en el encanto de estos gentleman." },
  { l = "es", t = "Te contamos algunos de los motivos por los que amarlos es un must-have." },
  { l = "es", t = "¿Por qué nos gustan los británicos?" },
  { l = "es", t = "- Porque solo ellos pueden llevar chaleco con estilo: bueno chaleco y otras cosas como bombín, gabardina, chaqué o incluso bastón." },
  { l = "es", t = "Nadie como los británicos puede lucir con estilazo todas y cada una de las prendas masculinas viejunas, perdón, clásicas." },
  { l = "es", t = "La prueba está la aporta Benedict Cumberbatch vestido de Sherlock Holmes." },
  { l = "es", t = "- Porque te abren la puerta del coche: esto es un anacronismo total y, de hecho, la apertura educada de puertas está en peligro de estinción." },
  { l = "es", t = "Sin embargo, no podemos evitar que nos guste y estamos seguras de que a Jude Law no se le olvidaría abrirnos: ¡luchemos por que no desaparezca apoyando a los gentleman!" },
  { l = "es", t = "- Porque toman el té a las 5: ¿hay algo más chic que un té con pastas al lado de Daniel Craig vestido de 007?" },
  { l = "es", t = "Aunque nos encanta que nos inviten a un gintonic o a un pincho de tortilla, de vez en cuando una merienda con glamour puede ser una sorpresa very nice." },
  { l = "es", t = "- Porque su acento nos vuelve locas: ¿pero nuestro favorito no era el acento argentino?" },
  { l = "es", t = "También." },
  { l = "es", t = "Podemos tener dos favoritos, solo que en los británicos juega a su favor que no entendemos lo que nos están diciendo." },
  { l = "es", t = "De hecho Crepúsculo nos gusta infinitamente más cuando no sabemos de que habla Robert Pattinson." },
  { l = "es", t = "- Porque no les cuesta decir Sorry: de hecho quizá lo dicen demasiado, pero no hay nada más sexy que un chico que sabe pedir perdón." },
  { l = "es", t = "De hecho a Luke Evans o a Hugh Grant, les perdonarías todo y lo sabes." },
  { l = "es", t = "- Porque envejecen mejor que nadie: si en Hollywood el rey de los maduritos es el recién casado George Clooney, en el Reino Unido la cosa queda entre Ewan McGregor, Hugh Laurie, Ralph Fiennes y Clive Owen." },
  { l = "es", t = "¡Imposible decidirse por uno solo!" },
  { l = "es", t = "- Porque son adorables... y lo sabes: una última razón de peso pero sin sentido, como todos los sentimientos en general." },
  { l = "es", t = "¿Verdad que son charming, cute and lovable?" },
  { l = "de-DE", t = "VAGABOND ist eine Qualitätsmarke, die für moderne, urbane Schuhe mit Vintage-Twist steht." },
  { l = "de-DE", t = "Beim Herstellungsprozess geht es immer um den Gesamtlook, die Linienführung und insbesondere um Tragekomfort und Tragbarkeit." },
  { l = "de-DE", t = "Aus diesem Grund ist VAGABOND bei einer Vielzahl von Menschen für ihre unverwechselbaren Schuhe beliebt, die immer komfortabel sind und stets das gewisse Etwas besitzen." },
  { l = "de-DE", t = "Zudem engagiert sich VAGABOND mit Leidenschaft für eine nachhaltige Produktion." },
  { l = "fr", t = "Bouchée ronde diamètre 80 mm x 24" },
  { l = "fr", t = "Bouchée ronde tradition" },
  { l = "fr", t = "Croûte en pâte feuilletée, destinée à recevoir une garniture." },
  { l = "fr", t = "Farine, matière grasse végétale (huile et graisse végétale, eau, colorant: bêta-carotène naturel E160aiii), eau, sel, jaune d’œuf, sucre glace amylacé, vinaigre blanc." },
  { l = "fr", t = "A conserver dans un endroit frais à l'abri de l'humidité" },
  { l = "fr", t = "Sache" },
  { l = "fr", t = "poly-éthylène alimentaire" },
  { l = "fr", t = "Carton" },
  { l = "fr", t = "Bouchée ronde diamètre 80 mm x 24 FR000000982 4" },
  { l = "en-US", t = "Host agency" },
  { l = "en-US", t = "By submitting a booking request, you accept the Wimdu [[[%{terms_and_conditions_link}]]] as well as the [[[%{additional_legal_clauses}]]] ." },
  { l = "es", t = "Soy <s0>Laura</s0>, una juguetona <s1>Escort en Madrid </s1>que anda a la caza de romeos y julietas con los que compartir las pasiones más intensas." },
  { l = "es", t = "Con mis ojos avellanados, estos muslos prietos y unos labios voluptuosos y juveniles, puedo darte todos los placeres que imaginas y muchos más de los que puedas llegar a soñar." },
  { l = "es", t = "A mis 24 años nada me gusta más relacionarme con solteros/as ardientes, explorar mis límites y poner en práctica algunas de mis habilidades ocultas." },
  { l = "es", t = "Adoro que se derritan entre mis brazos con el <s2>Dúplex</s2>, el <s3>Francés natural</s3>, la <s4>Actitud GFE</s4> o el <s5>Masaje erótico</s5>." },
  { l = "es", t = "Por si fuera poco, soy algo morbosa con las relaciones <s6>lésbicas </s6>y no tengo problemas para divertirme con <s7>parejas </s7>liberales." },
  { l = "es", t = "Si te gusta lo que ves y quieres dar una dentellada a la manzana prohibida, no dudes en llamarme." },
  { l = "es", t = "Tengo <s8>disponibilidad total</s8> para dar y recibir, ahora y siempre." },
  { l = "de-DE", t = "Schöne und qualitativ hochwertige LED-Deckenlampe" },
  { l = "de-DE", t = "Eine wirklich schöne Deckenleuchte wurde mir hier zugesendet, geliefert wurde mir eine Deckenleuchte mit 2 energiesparenden LED-Birnen und einer E14 Fassung sowie kleineres Montagewerkzeug." },
  { l = "de-DE", t = "Praktisch ist auch, dass man die Spots in jede Richtung ausrichten kann, somit passt die Lampe in jeden Raum hinein." },
  { l = "de-DE", t = "Von dem Design schaut für mich alles sehr zeitgemäß aus, schlicht und elegant, die Qualität ist für meine Begriffe sehr hochwertig von der Verarbeitung." },
  { l = "de-DE", t = "Eine wirklich tolle und schöne Deckenlampe, mit diesem Artikel kann man eigentlich keinen Fehler machen, zumal man die LED-Birnen gleich inklusive dabei hat." },
  { l = "de-DE", t = "LED Wandleuchte - 3 Watt / 250 Lumen" },
  { l = "de-DE", t = "Diese Leuchte ist eine Decken-/ Wandleuchte aus Metall mit einem ovalen Fuß, schlicht und einfach gehalten, kein Designobjekt mit besonderer Optik." },
  { l = "de-DE", t = "Artikel kam gut und sicher verpackt an." },
  { l = "de-DE", t = "Der LED GU10 Leuchteinsatz ist aus Glas und strahlt ein warmweißes Licht aus." },
  { l = "de-DE", t = "Das Gehäuse ist recht klein, erscheint auf den Bildern meiner Meinung nach größer." },
  { l = "de-DE", t = "Der Sockel ist recht unauffällig und die Lampe ist bei mir als Bild Beleuchtung im Hintergrund im Einsatz." },
  { l = "de-DE", t = "Die Montage ist recht einfach: Halterungsblech am Gehäuse lösen, dieses an die Wand bzw. Decke anschrauben und dann das Gehäuse aufsetzen und festschrauben." },
  { l = "de-DE", t = "Das Kabel wird, wie bei allen handelsüblichen Leuchten, mit einer in der Leuchte befestigten Lüsterklemme angeklemmt." },
  { l = "de-DE", t = "Ein Tütchen mit Kabelüberzügen und Schrauben sowie Dübel sind anbei." },
  { l = "de-DE", t = "Alles komplett zur Montage." },
  { l = "de-DE", t = "Sehr gut!" },
  { l = "de-DE", t = "Der Schwenkfuß lässt sich problemlos verstellen und ist aus Chrom, die Lampenfassung ist mit einer Standard Gu10 Fassung versehen, somit passen alle handelsüblichen GU10 Strahler hinein." },
  { l = "de-DE", t = "Damit lassen sich verschiedene Beleuchtungsarten durch Zukauf eines passenden GU10 Strahlers erzielen: sanft, hell, Punktstrahler etc." },
  { l = "fr", t = "Le Bélize est un pays à part en Amérique centrale, de par sa culture métissée entre Mayas, descendants d'Européens et Garifunas." },
  { l = "fr", t = "Mais aussi par l'usage de l'anglais au milieu de pays hispanophones." },
  { l = "fr", t = "San Ignacio est un concentré de ce mélange, de cette singularité." },
  { l = "fr", t = "Son marché coloré et animé est un régal pour les amateurs de rencontre et de découverte des spécificités locales." },
  { l = "fr", t = "Si la ville vaut la visite en elle-même, les alentours sont riches pour le voyageur !" },
  { l = "fr", t = "Que ce soit la découverte des vestiges mayas avec les ruines de Cahal Pech ou d'El Pilar, ou bien l'exploration des merveilles naturelles que réserve la région de Cayo, c'est une excellente base pour les amateurs d'écotourisme ou de tourisme d'aventure." },
  { l = "fr", t = "<g1>Tout est fait pour rendre le voyage facile à San Ignacio</g1>, avec une offre d'hébergement variée." },
  { l = "fr", t = "Mais pour autant, la ville garde son caractère, n'étant pas entièrement dédiée au tourisme." },
  { l = "fr", t = "Nous avons fait de très belles rencontres qui perdurent encore aujourd'hui, 2 ans après notre passage !" },
  { l = "fr", t = "Base idéale pour visiter le district de Cayo au Bélize, riche en ruines mayas et idéale pour les amateurs de nature, <g1>San Ignacio est une petite ville dynamique et accueillante</g1> pour les voyageurs." },
  { l = "fr", t = "Prenez le temps de flâner dans les alentours de la ville, de passer sur le marché." },
  { l = "fr", t = "Nul doute que vous serez abordé par <g1>les charmants habitants de San Ignacio</g1>, très ouverts et accueillants." },
  { l = "fr", t = "Les ruines maya sont un des nombreux attraits de la région de San Ignacio" },
  { l = "en-US", t = "Verbling Classes" },
  { l = "en-GB", t = "Did LEGO STAR WARS: The Force Awakens, Miniland Model Display prompt your visit today?" },
  { l = "es", t = "[ES] ¡Llega la segunda pecera!" },
  { l = "es", t = "Pecera de la tortuga" },
  { l = "es", t = "El día de ayer se introdujo la primera de las siete peceras que saldrán al catalogo en el transcurrir de los días." },
  { l = "es", t = "Cada una de ellas con un diseño diferente, con peces de distintas formas y de distintos colores, todo esto para que tu te hagas con ellas y decores tu sala de la mejor manera posible." },
  { l = "es", t = "Hoy te informamos nuevamente de la llegada de la segunda pecera, ¿quieres verla?" },
  { l = "es", t = "¡Sigue leyendo!" },
  { l = "es", t = "Así es, esta vez llega la segunda pecera, la cual, en su interior posee una bonita tortuga." },
  { l = "es", t = "Al igual que la anterior esta sale con un módico precio de 25 créditos y 25 diamantes." },
  { l = "es", t = "Pero no solo eso, puesto que si compras cualquiera de las peceras que salgan, recibirás una placa que represente dicha pecera." },
  { l = "es", t = "A continuación te mostramos los dos objetos que recibirás, claro, si lo compras." },
  { l = "es", t = "Coleccionista de tortugas Para adquirir la pecera de la tortuga" },
  { l = "es", t = "¿Qué te pareció esta segunda entrega?" },
  { l = "es", t = "¿Eres ya un verdadero coleccionista de peceras?" },
  { l = "es", t = "¿Has conseguido las dos que han salido?" },
  { l = "es", t = "¿Y piensas conseguir las demás?" },
  { l = "es", t = "No olvides dejarnos tu opinión en la siguiente caja de comentarios, tu opinión es muy importante para nosotros al momento de sacar a la luz las novedades del mundo virtual, Habbo." },
  { l = "de-DE", t = "Schönen guten Tag," },
  { l = "de-DE", t = "wir möchten uns bei Ihnen nochmals für Ihren Einkauf bedanken." },
  { l = "de-DE", t = "Sollten Sie noch irgendwelche Fragen haben, sind wir natürlich gerne für Sie da." },
  { l = "de-DE", t = "Sie haben bei uns leider eine negative Bewertung abgegeben." },
  { l = "de-DE", t = "Wir entschuldigen uns sehr für die fehlerhafte Produktbeschreibung unsererseits und es tut uns sehr leid." },
  { l = "de-DE", t = "Wir würden Ihnen gerne Folgendes vorschlagen: wenn Sie die Bewertung entfernen, erstatten wir Ihnen den vollen Betrag inklusive Versandkosten." },
  { l = "de-DE", t = "Wir wünschen Ihnen noch einen schönen Tag." },
} -- this line number - 2 == table size
table_size = 86

request = function()
   path = "/v2/check"
   wrk.method = "POST"
   wrk.headers["Content-Type"] = "application/x-www-form-urlencoded"

   index = math.random(table_size)
   lang = texts[index].l
   text = texts[index].t

   wrk.body   = "language=" .. lang .. "&text=" .. text

   return wrk.format(nil, path)
end
